apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pentest1
  
  description: pentest1
  
  annotations:
    github.com/project-slug: defra-adp-sandpit/pentest1
    dev.azure.com/project: pentest1
    dev.azure.com/build-definition: pentest1
    sonarqube.org/project-key: pentest1
    grafana/dashboard-selector: "folderTitle == 'Managed Prometheus'"
    backstage.io/kubernetes-id: pentest1
  links:
    - url: https://github.com/defra-adp-sandpit/pentest1
      title: GitHub Repository
      icon: github
    - url: https://dev.azure.com/defragovuk/pentest1/
      title: Azure DevOps Project
      icon: project
    - url: https://sonarcloud.io/project/overview?id=pentest1
      title: SonarCloud Analysis
      icon: check
    - url: https://snyk.io/test/github/DEFRA/pentest1
      title: Snyk Analysis
      icon: policy
    - url: https://portal.azure.com/defradev.onmicrosoft.com
      title: Azure Portal - Defra Dev
      icon: cloud
    - url: https://portal.azure.com/Defra.onmicrosoft.com
      title: Azure Portal - Defra
      icon: cloud
    - url: https://pentest1.snd3.adp.defra.gov.uk/
      title: SND3
    - url: https://pentest1.dev1.adp.defra.gov.uk/
      title: DEV1
    - url: https://pentest1.tst1.adp.defra.gov.uk/
      title: TST1
    - url: https://pentest1.pre1.adp.defra.gov.uk/
      title: PRE1
spec:
  type: frontend
  lifecycle: beta
  owner: "group:default/fcp-demo"
  
